### ISSUE TITLE
500 Error when importing RDA DCS plan

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#284]
```
Internal Server Error: /api/v2/plans/import/rda/
Traceback (most recent call last): 
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/src/easydmp/plan/api/v2/views.py", line 211, in import_rdadcs_via_json_post
    return self._import_rdadcs_plan(request, export_dict)
  File "/app/src/easydmp/plan/api/v2/views.py", line 184, in _import_rdadcs_plan
    pim = _import_rdadcs_plan(request, export_dict)
  File "/app/src/easydmp/plan/api/v2/views.py", line 77, in _import_rdadcs_plan
    return _import_plan(request, export_dict, wrapper)
  File "/app/src/easydmp/plan/api/v2/views.py", line 54, in _import_plan
    pim = importer(export_dict, request.user, via='API')
  File "/app/src/easydmp/plan/api/v2/views.py", line 75, in wrapper
    return importer.import_rdadcs()
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/src/easydmp/rdadcs/lib/import_plan.py", line 86, in import_rdadcs
    self.do_dataset(jsonblob['dataset'])
  File "/app/src/easydmp/rdadcs/lib/import_plan.py", line 347, in do_dataset
    self.do_single_dataset(entry, parent_path, answerset)
  File "/app/src/easydmp/rdadcs/lib/import_plan.py", line 366, in do_single_dataset
    self.do_distribution(jsonblob['distribution'], answerset)
  File "/app/src/easydmp/rdadcs/lib/import_plan.py", line 372, in do_distribution
    answerset = self.answersets.get(section=section, parent=parent)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
easydmp.plan.models.AnswerSet.DoesNotExist: AnswerSet matching query does not exist.
```

**Comment by hmpf** [comment]
This only occurs on the template-dev deployment, not in dev or prod.

**Comment by hmpf** [comment]
In the RDA-template in template-dev, the sections do not have super sections, no wonder it breaks. Time to hit the logs.

**Comment by hmpf** [comment]
The template-dev template has been brought in line with the others and import now works.
